/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AdminSession {
  'token' : AdminSessionToken,
  'createdAt' : Timestamp,
  'adminEmail' : string,
}
export type AdminSessionToken = string;
export interface AdminStats {
  'totalProducts' : bigint,
  'totalFiles' : bigint,
  'totalUsers' : bigint,
  'totalPosts' : bigint,
}
export interface AnalyticsResult {
  'userGrowth' : Array<DailyCount>,
  'postActivity' : Array<DailyCount>,
  'engagementStats' : EngagementStats,
}
export type CommentId = bigint;
export interface CommentView {
  'id' : CommentId,
  'authorAvatar' : [] | [ExternalBlob],
  'createdAt' : Timestamp,
  'text' : string,
  'authorName' : string,
  'author' : UserId,
  'postId' : PostId,
}
export interface DailyCount { 'date' : string, 'count' : bigint }
export interface EngagementStats {
  'avgLikesPerPost' : bigint,
  'totalLikes' : bigint,
  'totalComments' : bigint,
}
export type ExternalBlob = Uint8Array;
export type FileId = bigint;
export interface FileInput {
  'title' : string,
  'blob' : ExternalBlob,
  'description' : string,
}
export interface FileRecord {
  'id' : FileId,
  'title' : string,
  'uploaderName' : string,
  'blob' : ExternalBlob,
  'description' : string,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
}
export type FriendStatus = { 'none' : null } |
  { 'sent' : null } |
  { 'friends' : null } |
  { 'received' : null };
export interface FriendView {
  'status' : FriendStatus,
  'mutualFriendCount' : bigint,
  'username' : string,
  'userId' : UserId,
  'avatar' : [] | [ExternalBlob],
}
export type MediaType = { 'video' : null } |
  { 'image' : null };
export type ModerationAction = { 'approve' : null } |
  { 'delete' : null };
export type NotifId = bigint;
export type NotifType = { 'like_post' : null } |
  { 'friend_accept' : null } |
  { 'comment_post' : null } |
  { 'verified_granted' : null } |
  { 'friend_request' : null };
export interface Notification {
  'id' : NotifId,
  'actorName' : string,
  'notifType' : NotifType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'isRead' : boolean,
  'actorId' : UserId,
  'message' : string,
  'targetType' : [] | [string],
  'targetId' : [] | [bigint],
}
export type PostId = bigint;
export interface PostInput { 'text' : string, 'image' : [] | [ExternalBlob] }
export interface PostView {
  'id' : PostId,
  'likeCount' : bigint,
  'authorAvatar' : [] | [ExternalBlob],
  'createdAt' : Timestamp,
  'text' : string,
  'authorName' : string,
  'author' : UserId,
  'authorIsVerified' : boolean,
  'commentCount' : bigint,
  'image' : [] | [ExternalBlob],
  'likedByMe' : boolean,
  'flagCount' : bigint,
}
export interface Product {
  'id' : ProductId,
  'title' : string,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : string,
  'image' : [] | [ExternalBlob],
  'price' : number,
}
export type ProductId = bigint;
export interface ProductInput {
  'title' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
  'price' : number,
}
export interface Reel {
  'id' : ReelId,
  'title' : string,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : string,
  'description' : string,
  'likedBy' : Array<UserId>,
  'mediaUrl' : ExternalBlob,
  'authorIsVerified' : boolean,
  'savedBy' : Array<UserId>,
  'mediaType' : MediaType,
}
export type ReelId = bigint;
export interface ReelInput {
  'title' : string,
  'description' : string,
  'mediaUrl' : ExternalBlob,
  'mediaType' : MediaType,
}
export interface Story {
  'id' : StoryId,
  'expiresAt' : Timestamp,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : string,
  'viewedBy' : Array<UserId>,
  'image' : ExternalBlob,
}
export interface StoryGroup {
  'authorId' : UserId,
  'stories' : Array<Story>,
  'authorName' : string,
}
export type StoryId = bigint;
export interface StoryInput { 'image' : ExternalBlob }
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile {
  'id' : UserId,
  'bio' : [] | [string],
  'username' : string,
  'createdAt' : Timestamp,
  'coverPhoto' : [] | [ExternalBlob],
  'isVerified' : boolean,
  'isBanned' : boolean,
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _ImmutableObjectStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _ImmutableObjectStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _ImmutableObjectStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_immutableObjectStorageBlobsAreLive' : ActorMethod<
    [Array<Uint8Array>],
    Array<boolean>
  >,
  '_immutableObjectStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_immutableObjectStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_immutableObjectStorageCreateCertificate' : ActorMethod<
    [string],
    _ImmutableObjectStorageCreateCertificateResult
  >,
  '_immutableObjectStorageRefillCashier' : ActorMethod<
    [[] | [_ImmutableObjectStorageRefillInformation]],
    _ImmutableObjectStorageRefillResult
  >,
  '_immutableObjectStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'acceptFriendRequest' : ActorMethod<[UserId], undefined>,
  'addAdmin' : ActorMethod<[AdminSessionToken, string, string], undefined>,
  'addComment' : ActorMethod<[PostId, string], CommentView>,
  'adminBanUser' : ActorMethod<[AdminSessionToken, UserId], undefined>,
  'adminLogin' : ActorMethod<[string, string], [] | [AdminSession]>,
  'adminLogout' : ActorMethod<[AdminSessionToken], undefined>,
  'adminUnbanUser' : ActorMethod<[AdminSessionToken, UserId], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'banUser' : ActorMethod<[AdminSessionToken, UserId], undefined>,
  'cancelFriendRequest' : ActorMethod<[UserId], undefined>,
  'createPost' : ActorMethod<[PostInput], PostView>,
  'createProduct' : ActorMethod<[ProductInput], Product>,
  'createReel' : ActorMethod<[ReelInput], Reel>,
  'createStory' : ActorMethod<[StoryInput], Story>,
  'deleteComment' : ActorMethod<[CommentId], boolean>,
  'deleteFile' : ActorMethod<[FileId], boolean>,
  'deletePost' : ActorMethod<[PostId], boolean>,
  'deleteProduct' : ActorMethod<[ProductId], boolean>,
  'deleteReel' : ActorMethod<[ReelId], boolean>,
  'deleteStory' : ActorMethod<[StoryId], boolean>,
  'deleteUser' : ActorMethod<[AdminSessionToken, UserId], undefined>,
  'flagPost' : ActorMethod<[PostId, string], undefined>,
  'getAdminStats' : ActorMethod<[AdminSessionToken], AdminStats>,
  'getAllUsers' : ActorMethod<
    [AdminSessionToken, bigint, bigint],
    Array<UserProfile>
  >,
  'getAnalytics' : ActorMethod<[AdminSessionToken], AnalyticsResult>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getFlaggedPosts' : ActorMethod<[AdminSessionToken], Array<PostView>>,
  'getFriendRequests' : ActorMethod<[], Array<FriendView>>,
  'getFriendSuggestions' : ActorMethod<[], Array<FriendView>>,
  'getFriends' : ActorMethod<[], Array<FriendView>>,
  'getNewsfeed' : ActorMethod<[], Array<PostView>>,
  'getNotifications' : ActorMethod<[], Array<Notification>>,
  'getPostComments' : ActorMethod<[PostId], Array<CommentView>>,
  'getReels' : ActorMethod<[bigint, bigint], Array<Reel>>,
  'getSentRequests' : ActorMethod<[], Array<FriendView>>,
  'getStories' : ActorMethod<[], Array<StoryGroup>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'grantVerifiedTick' : ActorMethod<[AdminSessionToken, UserId], undefined>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likePost' : ActorMethod<[PostId], boolean>,
  'likeReel' : ActorMethod<[ReelId], boolean>,
  'listAdmins' : ActorMethod<[AdminSessionToken], Array<string>>,
  'listFiles' : ActorMethod<[], Array<FileRecord>>,
  'listProducts' : ActorMethod<[], Array<Product>>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[NotifId], undefined>,
  'markStoryViewed' : ActorMethod<[StoryId], undefined>,
  'moderatePost' : ActorMethod<
    [AdminSessionToken, PostId, ModerationAction],
    undefined
  >,
  'rejectFriendRequest' : ActorMethod<[UserId], undefined>,
  'removeAdmin' : ActorMethod<[AdminSessionToken, string], undefined>,
  'revokeVerifiedTick' : ActorMethod<[AdminSessionToken, UserId], undefined>,
  'saveCallerUserProfile' : ActorMethod<
    [string, [] | [ExternalBlob]],
    undefined
  >,
  'saveReel' : ActorMethod<[ReelId], boolean>,
  'sendFriendRequest' : ActorMethod<[UserId], undefined>,
  'unbanUser' : ActorMethod<[AdminSessionToken, UserId], undefined>,
  'unfriend' : ActorMethod<[UserId], undefined>,
  'updateProfileAvatar' : ActorMethod<[ExternalBlob], undefined>,
  'updateProfileBio' : ActorMethod<[string], undefined>,
  'updateProfileCoverPhoto' : ActorMethod<[ExternalBlob], undefined>,
  'updateProfileUsername' : ActorMethod<[string], undefined>,
  'uploadFile' : ActorMethod<[FileInput], FileRecord>,
  'validateAdminSession' : ActorMethod<[AdminSessionToken], boolean>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];