/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _ImmutableObjectStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _ImmutableObjectStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserId = IDL.Principal;
export const AdminSessionToken = IDL.Text;
export const PostId = IDL.Nat;
export const CommentId = IDL.Nat;
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Timestamp = IDL.Int;
export const CommentView = IDL.Record({
  'id' : CommentId,
  'authorAvatar' : IDL.Opt(ExternalBlob),
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : UserId,
  'postId' : PostId,
});
export const AdminSession = IDL.Record({
  'token' : AdminSessionToken,
  'createdAt' : Timestamp,
  'adminEmail' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PostInput = IDL.Record({
  'text' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const PostView = IDL.Record({
  'id' : PostId,
  'likeCount' : IDL.Nat,
  'authorAvatar' : IDL.Opt(ExternalBlob),
  'createdAt' : Timestamp,
  'text' : IDL.Text,
  'authorName' : IDL.Text,
  'author' : UserId,
  'authorIsVerified' : IDL.Bool,
  'commentCount' : IDL.Nat,
  'image' : IDL.Opt(ExternalBlob),
  'likedByMe' : IDL.Bool,
  'flagCount' : IDL.Nat,
});
export const ProductInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Float64,
});
export const ProductId = IDL.Nat;
export const Product = IDL.Record({
  'id' : ProductId,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'createdBy' : UserId,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Float64,
});
export const MediaType = IDL.Variant({
  'video' : IDL.Null,
  'image' : IDL.Null,
});
export const ReelInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'mediaUrl' : ExternalBlob,
  'mediaType' : MediaType,
});
export const ReelId = IDL.Nat;
export const Reel = IDL.Record({
  'id' : ReelId,
  'title' : IDL.Text,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
  'description' : IDL.Text,
  'likedBy' : IDL.Vec(UserId),
  'mediaUrl' : ExternalBlob,
  'authorIsVerified' : IDL.Bool,
  'savedBy' : IDL.Vec(UserId),
  'mediaType' : MediaType,
});
export const StoryInput = IDL.Record({ 'image' : ExternalBlob });
export const StoryId = IDL.Nat;
export const Story = IDL.Record({
  'id' : StoryId,
  'expiresAt' : Timestamp,
  'authorId' : UserId,
  'createdAt' : Timestamp,
  'authorName' : IDL.Text,
  'viewedBy' : IDL.Vec(UserId),
  'image' : ExternalBlob,
});
export const FileId = IDL.Nat;
export const AdminStats = IDL.Record({
  'totalProducts' : IDL.Nat,
  'totalFiles' : IDL.Nat,
  'totalUsers' : IDL.Nat,
  'totalPosts' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'id' : UserId,
  'bio' : IDL.Opt(IDL.Text),
  'username' : IDL.Text,
  'createdAt' : Timestamp,
  'coverPhoto' : IDL.Opt(ExternalBlob),
  'isVerified' : IDL.Bool,
  'isBanned' : IDL.Bool,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const DailyCount = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
export const EngagementStats = IDL.Record({
  'avgLikesPerPost' : IDL.Nat,
  'totalLikes' : IDL.Nat,
  'totalComments' : IDL.Nat,
});
export const AnalyticsResult = IDL.Record({
  'userGrowth' : IDL.Vec(DailyCount),
  'postActivity' : IDL.Vec(DailyCount),
  'engagementStats' : EngagementStats,
});
export const FriendStatus = IDL.Variant({
  'none' : IDL.Null,
  'sent' : IDL.Null,
  'friends' : IDL.Null,
  'received' : IDL.Null,
});
export const FriendView = IDL.Record({
  'status' : FriendStatus,
  'mutualFriendCount' : IDL.Nat,
  'username' : IDL.Text,
  'userId' : UserId,
  'avatar' : IDL.Opt(ExternalBlob),
});
export const NotifId = IDL.Nat;
export const NotifType = IDL.Variant({
  'like_post' : IDL.Null,
  'friend_accept' : IDL.Null,
  'comment_post' : IDL.Null,
  'verified_granted' : IDL.Null,
  'friend_request' : IDL.Null,
});
export const Notification = IDL.Record({
  'id' : NotifId,
  'actorName' : IDL.Text,
  'notifType' : NotifType,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'isRead' : IDL.Bool,
  'actorId' : UserId,
  'message' : IDL.Text,
  'targetType' : IDL.Opt(IDL.Text),
  'targetId' : IDL.Opt(IDL.Nat),
});
export const StoryGroup = IDL.Record({
  'authorId' : UserId,
  'stories' : IDL.Vec(Story),
  'authorName' : IDL.Text,
});
export const FileRecord = IDL.Record({
  'id' : FileId,
  'title' : IDL.Text,
  'uploaderName' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
  'uploadedAt' : Timestamp,
  'uploadedBy' : UserId,
});
export const ModerationAction = IDL.Variant({
  'approve' : IDL.Null,
  'delete' : IDL.Null,
});
export const FileInput = IDL.Record({
  'title' : IDL.Text,
  'blob' : ExternalBlob,
  'description' : IDL.Text,
});

export const idlService = IDL.Service({
  '_immutableObjectStorageBlobsAreLive' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [IDL.Vec(IDL.Bool)],
      ['query'],
    ),
  '_immutableObjectStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_immutableObjectStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_ImmutableObjectStorageCreateCertificateResult],
      [],
    ),
  '_immutableObjectStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
      [_ImmutableObjectStorageRefillResult],
      [],
    ),
  '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControl' : IDL.Func([], [], []),
  'acceptFriendRequest' : IDL.Func([UserId], [], []),
  'addAdmin' : IDL.Func([AdminSessionToken, IDL.Text, IDL.Text], [], []),
  'addComment' : IDL.Func([PostId, IDL.Text], [CommentView], []),
  'adminBanUser' : IDL.Func([AdminSessionToken, UserId], [], []),
  'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(AdminSession)], []),
  'adminLogout' : IDL.Func([AdminSessionToken], [], []),
  'adminUnbanUser' : IDL.Func([AdminSessionToken, UserId], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'banUser' : IDL.Func([AdminSessionToken, UserId], [], []),
  'cancelFriendRequest' : IDL.Func([UserId], [], []),
  'createPost' : IDL.Func([PostInput], [PostView], []),
  'createProduct' : IDL.Func([ProductInput], [Product], []),
  'createReel' : IDL.Func([ReelInput], [Reel], []),
  'createStory' : IDL.Func([StoryInput], [Story], []),
  'deleteComment' : IDL.Func([CommentId], [IDL.Bool], []),
  'deleteFile' : IDL.Func([FileId], [IDL.Bool], []),
  'deletePost' : IDL.Func([PostId], [IDL.Bool], []),
  'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
  'deleteReel' : IDL.Func([ReelId], [IDL.Bool], []),
  'deleteStory' : IDL.Func([StoryId], [IDL.Bool], []),
  'deleteUser' : IDL.Func([AdminSessionToken, UserId], [], []),
  'flagPost' : IDL.Func([PostId, IDL.Text], [], []),
  'getAdminStats' : IDL.Func([AdminSessionToken], [AdminStats], ['query']),
  'getAllUsers' : IDL.Func(
      [AdminSessionToken, IDL.Nat, IDL.Nat],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'getAnalytics' : IDL.Func([AdminSessionToken], [AnalyticsResult], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getFlaggedPosts' : IDL.Func(
      [AdminSessionToken],
      [IDL.Vec(PostView)],
      ['query'],
    ),
  'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendView)], ['query']),
  'getFriendSuggestions' : IDL.Func([], [IDL.Vec(FriendView)], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(FriendView)], ['query']),
  'getNewsfeed' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
  'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getPostComments' : IDL.Func([PostId], [IDL.Vec(CommentView)], ['query']),
  'getReels' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Reel)], ['query']),
  'getSentRequests' : IDL.Func([], [IDL.Vec(FriendView)], ['query']),
  'getStories' : IDL.Func([], [IDL.Vec(StoryGroup)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'grantVerifiedTick' : IDL.Func([AdminSessionToken, UserId], [], []),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likePost' : IDL.Func([PostId], [IDL.Bool], []),
  'likeReel' : IDL.Func([ReelId], [IDL.Bool], []),
  'listAdmins' : IDL.Func([AdminSessionToken], [IDL.Vec(IDL.Text)], ['query']),
  'listFiles' : IDL.Func([], [IDL.Vec(FileRecord)], ['query']),
  'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([NotifId], [], []),
  'markStoryViewed' : IDL.Func([StoryId], [], []),
  'moderatePost' : IDL.Func(
      [AdminSessionToken, PostId, ModerationAction],
      [],
      [],
    ),
  'rejectFriendRequest' : IDL.Func([UserId], [], []),
  'removeAdmin' : IDL.Func([AdminSessionToken, IDL.Text], [], []),
  'revokeVerifiedTick' : IDL.Func([AdminSessionToken, UserId], [], []),
  'saveCallerUserProfile' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'saveReel' : IDL.Func([ReelId], [IDL.Bool], []),
  'sendFriendRequest' : IDL.Func([UserId], [], []),
  'unbanUser' : IDL.Func([AdminSessionToken, UserId], [], []),
  'unfriend' : IDL.Func([UserId], [], []),
  'updateProfileAvatar' : IDL.Func([ExternalBlob], [], []),
  'updateProfileBio' : IDL.Func([IDL.Text], [], []),
  'updateProfileCoverPhoto' : IDL.Func([ExternalBlob], [], []),
  'updateProfileUsername' : IDL.Func([IDL.Text], [], []),
  'uploadFile' : IDL.Func([FileInput], [FileRecord], []),
  'validateAdminSession' : IDL.Func([AdminSessionToken], [IDL.Bool], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _ImmutableObjectStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _ImmutableObjectStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _ImmutableObjectStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserId = IDL.Principal;
  const AdminSessionToken = IDL.Text;
  const PostId = IDL.Nat;
  const CommentId = IDL.Nat;
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Timestamp = IDL.Int;
  const CommentView = IDL.Record({
    'id' : CommentId,
    'authorAvatar' : IDL.Opt(ExternalBlob),
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : UserId,
    'postId' : PostId,
  });
  const AdminSession = IDL.Record({
    'token' : AdminSessionToken,
    'createdAt' : Timestamp,
    'adminEmail' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PostInput = IDL.Record({
    'text' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const PostView = IDL.Record({
    'id' : PostId,
    'likeCount' : IDL.Nat,
    'authorAvatar' : IDL.Opt(ExternalBlob),
    'createdAt' : Timestamp,
    'text' : IDL.Text,
    'authorName' : IDL.Text,
    'author' : UserId,
    'authorIsVerified' : IDL.Bool,
    'commentCount' : IDL.Nat,
    'image' : IDL.Opt(ExternalBlob),
    'likedByMe' : IDL.Bool,
    'flagCount' : IDL.Nat,
  });
  const ProductInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Float64,
  });
  const ProductId = IDL.Nat;
  const Product = IDL.Record({
    'id' : ProductId,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'createdBy' : UserId,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Float64,
  });
  const MediaType = IDL.Variant({ 'video' : IDL.Null, 'image' : IDL.Null });
  const ReelInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'mediaUrl' : ExternalBlob,
    'mediaType' : MediaType,
  });
  const ReelId = IDL.Nat;
  const Reel = IDL.Record({
    'id' : ReelId,
    'title' : IDL.Text,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
    'description' : IDL.Text,
    'likedBy' : IDL.Vec(UserId),
    'mediaUrl' : ExternalBlob,
    'authorIsVerified' : IDL.Bool,
    'savedBy' : IDL.Vec(UserId),
    'mediaType' : MediaType,
  });
  const StoryInput = IDL.Record({ 'image' : ExternalBlob });
  const StoryId = IDL.Nat;
  const Story = IDL.Record({
    'id' : StoryId,
    'expiresAt' : Timestamp,
    'authorId' : UserId,
    'createdAt' : Timestamp,
    'authorName' : IDL.Text,
    'viewedBy' : IDL.Vec(UserId),
    'image' : ExternalBlob,
  });
  const FileId = IDL.Nat;
  const AdminStats = IDL.Record({
    'totalProducts' : IDL.Nat,
    'totalFiles' : IDL.Nat,
    'totalUsers' : IDL.Nat,
    'totalPosts' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'id' : UserId,
    'bio' : IDL.Opt(IDL.Text),
    'username' : IDL.Text,
    'createdAt' : Timestamp,
    'coverPhoto' : IDL.Opt(ExternalBlob),
    'isVerified' : IDL.Bool,
    'isBanned' : IDL.Bool,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const DailyCount = IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat });
  const EngagementStats = IDL.Record({
    'avgLikesPerPost' : IDL.Nat,
    'totalLikes' : IDL.Nat,
    'totalComments' : IDL.Nat,
  });
  const AnalyticsResult = IDL.Record({
    'userGrowth' : IDL.Vec(DailyCount),
    'postActivity' : IDL.Vec(DailyCount),
    'engagementStats' : EngagementStats,
  });
  const FriendStatus = IDL.Variant({
    'none' : IDL.Null,
    'sent' : IDL.Null,
    'friends' : IDL.Null,
    'received' : IDL.Null,
  });
  const FriendView = IDL.Record({
    'status' : FriendStatus,
    'mutualFriendCount' : IDL.Nat,
    'username' : IDL.Text,
    'userId' : UserId,
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const NotifId = IDL.Nat;
  const NotifType = IDL.Variant({
    'like_post' : IDL.Null,
    'friend_accept' : IDL.Null,
    'comment_post' : IDL.Null,
    'verified_granted' : IDL.Null,
    'friend_request' : IDL.Null,
  });
  const Notification = IDL.Record({
    'id' : NotifId,
    'actorName' : IDL.Text,
    'notifType' : NotifType,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'isRead' : IDL.Bool,
    'actorId' : UserId,
    'message' : IDL.Text,
    'targetType' : IDL.Opt(IDL.Text),
    'targetId' : IDL.Opt(IDL.Nat),
  });
  const StoryGroup = IDL.Record({
    'authorId' : UserId,
    'stories' : IDL.Vec(Story),
    'authorName' : IDL.Text,
  });
  const FileRecord = IDL.Record({
    'id' : FileId,
    'title' : IDL.Text,
    'uploaderName' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
    'uploadedAt' : Timestamp,
    'uploadedBy' : UserId,
  });
  const ModerationAction = IDL.Variant({
    'approve' : IDL.Null,
    'delete' : IDL.Null,
  });
  const FileInput = IDL.Record({
    'title' : IDL.Text,
    'blob' : ExternalBlob,
    'description' : IDL.Text,
  });
  
  return IDL.Service({
    '_immutableObjectStorageBlobsAreLive' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [IDL.Vec(IDL.Bool)],
        ['query'],
      ),
    '_immutableObjectStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_immutableObjectStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_immutableObjectStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_ImmutableObjectStorageCreateCertificateResult],
        [],
      ),
    '_immutableObjectStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_ImmutableObjectStorageRefillInformation)],
        [_ImmutableObjectStorageRefillResult],
        [],
      ),
    '_immutableObjectStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControl' : IDL.Func([], [], []),
    'acceptFriendRequest' : IDL.Func([UserId], [], []),
    'addAdmin' : IDL.Func([AdminSessionToken, IDL.Text, IDL.Text], [], []),
    'addComment' : IDL.Func([PostId, IDL.Text], [CommentView], []),
    'adminBanUser' : IDL.Func([AdminSessionToken, UserId], [], []),
    'adminLogin' : IDL.Func([IDL.Text, IDL.Text], [IDL.Opt(AdminSession)], []),
    'adminLogout' : IDL.Func([AdminSessionToken], [], []),
    'adminUnbanUser' : IDL.Func([AdminSessionToken, UserId], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'banUser' : IDL.Func([AdminSessionToken, UserId], [], []),
    'cancelFriendRequest' : IDL.Func([UserId], [], []),
    'createPost' : IDL.Func([PostInput], [PostView], []),
    'createProduct' : IDL.Func([ProductInput], [Product], []),
    'createReel' : IDL.Func([ReelInput], [Reel], []),
    'createStory' : IDL.Func([StoryInput], [Story], []),
    'deleteComment' : IDL.Func([CommentId], [IDL.Bool], []),
    'deleteFile' : IDL.Func([FileId], [IDL.Bool], []),
    'deletePost' : IDL.Func([PostId], [IDL.Bool], []),
    'deleteProduct' : IDL.Func([ProductId], [IDL.Bool], []),
    'deleteReel' : IDL.Func([ReelId], [IDL.Bool], []),
    'deleteStory' : IDL.Func([StoryId], [IDL.Bool], []),
    'deleteUser' : IDL.Func([AdminSessionToken, UserId], [], []),
    'flagPost' : IDL.Func([PostId, IDL.Text], [], []),
    'getAdminStats' : IDL.Func([AdminSessionToken], [AdminStats], ['query']),
    'getAllUsers' : IDL.Func(
        [AdminSessionToken, IDL.Nat, IDL.Nat],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'getAnalytics' : IDL.Func(
        [AdminSessionToken],
        [AnalyticsResult],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getFlaggedPosts' : IDL.Func(
        [AdminSessionToken],
        [IDL.Vec(PostView)],
        ['query'],
      ),
    'getFriendRequests' : IDL.Func([], [IDL.Vec(FriendView)], ['query']),
    'getFriendSuggestions' : IDL.Func([], [IDL.Vec(FriendView)], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(FriendView)], ['query']),
    'getNewsfeed' : IDL.Func([], [IDL.Vec(PostView)], ['query']),
    'getNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getPostComments' : IDL.Func([PostId], [IDL.Vec(CommentView)], ['query']),
    'getReels' : IDL.Func([IDL.Nat, IDL.Nat], [IDL.Vec(Reel)], ['query']),
    'getSentRequests' : IDL.Func([], [IDL.Vec(FriendView)], ['query']),
    'getStories' : IDL.Func([], [IDL.Vec(StoryGroup)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'grantVerifiedTick' : IDL.Func([AdminSessionToken, UserId], [], []),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likePost' : IDL.Func([PostId], [IDL.Bool], []),
    'likeReel' : IDL.Func([ReelId], [IDL.Bool], []),
    'listAdmins' : IDL.Func(
        [AdminSessionToken],
        [IDL.Vec(IDL.Text)],
        ['query'],
      ),
    'listFiles' : IDL.Func([], [IDL.Vec(FileRecord)], ['query']),
    'listProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([NotifId], [], []),
    'markStoryViewed' : IDL.Func([StoryId], [], []),
    'moderatePost' : IDL.Func(
        [AdminSessionToken, PostId, ModerationAction],
        [],
        [],
      ),
    'rejectFriendRequest' : IDL.Func([UserId], [], []),
    'removeAdmin' : IDL.Func([AdminSessionToken, IDL.Text], [], []),
    'revokeVerifiedTick' : IDL.Func([AdminSessionToken, UserId], [], []),
    'saveCallerUserProfile' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'saveReel' : IDL.Func([ReelId], [IDL.Bool], []),
    'sendFriendRequest' : IDL.Func([UserId], [], []),
    'unbanUser' : IDL.Func([AdminSessionToken, UserId], [], []),
    'unfriend' : IDL.Func([UserId], [], []),
    'updateProfileAvatar' : IDL.Func([ExternalBlob], [], []),
    'updateProfileBio' : IDL.Func([IDL.Text], [], []),
    'updateProfileCoverPhoto' : IDL.Func([ExternalBlob], [], []),
    'updateProfileUsername' : IDL.Func([IDL.Text], [], []),
    'uploadFile' : IDL.Func([FileInput], [FileRecord], []),
    'validateAdminSession' : IDL.Func(
        [AdminSessionToken],
        [IDL.Bool],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };