/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Reel {
    id: ReelId;
    title: string;
    authorId: UserId;
    createdAt: Timestamp;
    authorName: string;
    description: string;
    likedBy: Array<UserId>;
    mediaUrl: ExternalBlob;
    authorIsVerified: boolean;
    savedBy: Array<UserId>;
    mediaType: MediaType;
}
export type ReelId = bigint;
export type Timestamp = bigint;
export interface Product {
    id: ProductId;
    title: string;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
    image?: ExternalBlob;
    price: number;
}
export interface FileInput {
    title: string;
    blob: ExternalBlob;
    description: string;
}
export type PostId = bigint;
export interface PostView {
    id: PostId;
    likeCount: bigint;
    authorAvatar?: ExternalBlob;
    createdAt: Timestamp;
    text: string;
    authorName: string;
    author: UserId;
    authorIsVerified: boolean;
    commentCount: bigint;
    image?: ExternalBlob;
    likedByMe: boolean;
    flagCount: bigint;
}
export interface AnalyticsResult {
    userGrowth: Array<DailyCount>;
    postActivity: Array<DailyCount>;
    engagementStats: EngagementStats;
}
export interface AdminSession {
    token: AdminSessionToken;
    createdAt: Timestamp;
    adminEmail: string;
}
export interface _ImmutableObjectStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface DailyCount {
    date: string;
    count: bigint;
}
export interface ReelInput {
    title: string;
    description: string;
    mediaUrl: ExternalBlob;
    mediaType: MediaType;
}
export interface StoryInput {
    image: ExternalBlob;
}
export type NotifId = bigint;
export interface ProductInput {
    title: string;
    description: string;
    image?: ExternalBlob;
    price: number;
}
export type CommentId = bigint;
export interface StoryGroup {
    authorId: UserId;
    stories: Array<Story>;
    authorName: string;
}
export interface _ImmutableObjectStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export type StoryId = bigint;
export interface _ImmutableObjectStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Story {
    id: StoryId;
    expiresAt: Timestamp;
    authorId: UserId;
    createdAt: Timestamp;
    authorName: string;
    viewedBy: Array<UserId>;
    image: ExternalBlob;
}
export interface EngagementStats {
    avgLikesPerPost: bigint;
    totalLikes: bigint;
    totalComments: bigint;
}
export interface CommentView {
    id: CommentId;
    authorAvatar?: ExternalBlob;
    createdAt: Timestamp;
    text: string;
    authorName: string;
    author: UserId;
    postId: PostId;
}
export type UserId = Principal;
export interface AdminStats {
    totalProducts: bigint;
    totalFiles: bigint;
    totalUsers: bigint;
    totalPosts: bigint;
}
export interface Notification {
    id: NotifId;
    actorName: string;
    notifType: NotifType;
    userId: UserId;
    createdAt: Timestamp;
    isRead: boolean;
    actorId: UserId;
    message: string;
    targetType?: string;
    targetId?: bigint;
}
export interface FileRecord {
    id: FileId;
    title: string;
    uploaderName: string;
    blob: ExternalBlob;
    description: string;
    uploadedAt: Timestamp;
    uploadedBy: UserId;
}
export type ProductId = bigint;
export interface PostInput {
    text: string;
    image?: ExternalBlob;
}
export type FileId = bigint;
export type AdminSessionToken = string;
export interface UserProfile {
    id: UserId;
    bio?: string;
    username: string;
    createdAt: Timestamp;
    coverPhoto?: ExternalBlob;
    isVerified: boolean;
    isBanned: boolean;
    avatar?: ExternalBlob;
}
export interface FriendView {
    status: FriendStatus;
    mutualFriendCount: bigint;
    username: string;
    userId: UserId;
    avatar?: ExternalBlob;
}
export enum FriendStatus {
    none = "none",
    sent = "sent",
    friends = "friends",
    received = "received"
}
export enum MediaType {
    video = "video",
    image = "image"
}
export enum ModerationAction {
    approve = "approve",
    delete_ = "delete"
}
export enum NotifType {
    like_post = "like_post",
    friend_accept = "friend_accept",
    comment_post = "comment_post",
    verified_granted = "verified_granted",
    friend_request = "friend_request"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _immutableObjectStorageBlobsAreLive(hashes: Array<Uint8Array>): Promise<Array<boolean>>;
    _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _immutableObjectStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _immutableObjectStorageCreateCertificate(blobHash: string): Promise<_ImmutableObjectStorageCreateCertificateResult>;
    _immutableObjectStorageRefillCashier(refillInformation: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult>;
    _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControl(): Promise<void>;
    acceptFriendRequest(from: UserId): Promise<void>;
    addAdmin(token: AdminSessionToken, email: string, password: string): Promise<void>;
    addComment(postId: PostId, text: string): Promise<CommentView>;
    adminBanUser(token: AdminSessionToken, userId: UserId): Promise<void>;
    adminLogin(email: string, password: string): Promise<AdminSession | null>;
    adminLogout(token: AdminSessionToken): Promise<void>;
    adminUnbanUser(token: AdminSessionToken, userId: UserId): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    banUser(token: AdminSessionToken, userId: UserId): Promise<void>;
    cancelFriendRequest(to: UserId): Promise<void>;
    createPost(input: PostInput): Promise<PostView>;
    createProduct(input: ProductInput): Promise<Product>;
    createReel(input: ReelInput): Promise<Reel>;
    createStory(input: StoryInput): Promise<Story>;
    deleteComment(commentId: CommentId): Promise<boolean>;
    deleteFile(fileId: FileId): Promise<boolean>;
    deletePost(postId: PostId): Promise<boolean>;
    deleteProduct(productId: ProductId): Promise<boolean>;
    deleteReel(reelId: ReelId): Promise<boolean>;
    deleteStory(storyId: StoryId): Promise<boolean>;
    deleteUser(token: AdminSessionToken, userId: UserId): Promise<void>;
    flagPost(postId: PostId, reason: string): Promise<void>;
    getAdminStats(token: AdminSessionToken): Promise<AdminStats>;
    getAllUsers(token: AdminSessionToken, page: bigint, pageSize: bigint): Promise<Array<UserProfile>>;
    getAnalytics(token: AdminSessionToken): Promise<AnalyticsResult>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getFlaggedPosts(token: AdminSessionToken): Promise<Array<PostView>>;
    getFriendRequests(): Promise<Array<FriendView>>;
    getFriendSuggestions(): Promise<Array<FriendView>>;
    getFriends(): Promise<Array<FriendView>>;
    getNewsfeed(): Promise<Array<PostView>>;
    getNotifications(): Promise<Array<Notification>>;
    getPostComments(postId: PostId): Promise<Array<CommentView>>;
    getReels(page: bigint, pageSize: bigint): Promise<Array<Reel>>;
    getSentRequests(): Promise<Array<FriendView>>;
    getStories(): Promise<Array<StoryGroup>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    grantVerifiedTick(token: AdminSessionToken, userId: UserId): Promise<void>;
    isCallerAdmin(): Promise<boolean>;
    likePost(postId: PostId): Promise<boolean>;
    likeReel(reelId: ReelId): Promise<boolean>;
    listAdmins(token: AdminSessionToken): Promise<Array<string>>;
    listFiles(): Promise<Array<FileRecord>>;
    listProducts(): Promise<Array<Product>>;
    markAllNotificationsRead(): Promise<void>;
    markNotificationRead(notifId: NotifId): Promise<void>;
    markStoryViewed(storyId: StoryId): Promise<void>;
    moderatePost(token: AdminSessionToken, postId: PostId, action: ModerationAction): Promise<void>;
    rejectFriendRequest(from: UserId): Promise<void>;
    removeAdmin(token: AdminSessionToken, email: string): Promise<void>;
    revokeVerifiedTick(token: AdminSessionToken, userId: UserId): Promise<void>;
    saveCallerUserProfile(username: string, avatar: ExternalBlob | null): Promise<void>;
    saveReel(reelId: ReelId): Promise<boolean>;
    sendFriendRequest(to: UserId): Promise<void>;
    unbanUser(token: AdminSessionToken, userId: UserId): Promise<void>;
    unfriend(userId: UserId): Promise<void>;
    updateProfileAvatar(avatar: ExternalBlob): Promise<void>;
    updateProfileBio(bio: string): Promise<void>;
    updateProfileCoverPhoto(coverPhoto: ExternalBlob): Promise<void>;
    updateProfileUsername(username: string): Promise<void>;
    uploadFile(input: FileInput): Promise<FileRecord>;
    validateAdminSession(token: AdminSessionToken): Promise<boolean>;
}
import type { AdminSession as _AdminSession, CommentId as _CommentId, CommentView as _CommentView, ExternalBlob as _ExternalBlob, FileId as _FileId, FileInput as _FileInput, FileRecord as _FileRecord, FriendStatus as _FriendStatus, FriendView as _FriendView, MediaType as _MediaType, ModerationAction as _ModerationAction, NotifId as _NotifId, NotifType as _NotifType, Notification as _Notification, PostId as _PostId, PostInput as _PostInput, PostView as _PostView, Product as _Product, ProductId as _ProductId, ProductInput as _ProductInput, Reel as _Reel, ReelId as _ReelId, ReelInput as _ReelInput, Story as _Story, StoryGroup as _StoryGroup, StoryId as _StoryId, StoryInput as _StoryInput, Timestamp as _Timestamp, UserId as _UserId, UserProfile as _UserProfile, UserRole as _UserRole, _ImmutableObjectStorageRefillInformation as __ImmutableObjectStorageRefillInformation, _ImmutableObjectStorageRefillResult as __ImmutableObjectStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _immutableObjectStorageBlobsAreLive(arg0: Array<Uint8Array>): Promise<Array<boolean>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsAreLive(arg0);
            return result;
        }
    }
    async _immutableObjectStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageBlobsToDelete();
            return result;
        }
    }
    async _immutableObjectStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _immutableObjectStorageCreateCertificate(arg0: string): Promise<_ImmutableObjectStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _immutableObjectStorageRefillCashier(arg0: _ImmutableObjectStorageRefillInformation | null): Promise<_ImmutableObjectStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__ImmutableObjectStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _immutableObjectStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._immutableObjectStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async acceptFriendRequest(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.acceptFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.acceptFriendRequest(arg0);
            return result;
        }
    }
    async addAdmin(arg0: AdminSessionToken, arg1: string, arg2: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addAdmin(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addAdmin(arg0, arg1, arg2);
            return result;
        }
    }
    async addComment(arg0: PostId, arg1: string): Promise<CommentView> {
        if (this.processError) {
            try {
                const result = await this.actor.addComment(arg0, arg1);
                return from_candid_CommentView_n8(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addComment(arg0, arg1);
            return from_candid_CommentView_n8(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminBanUser(arg0: AdminSessionToken, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminBanUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminBanUser(arg0, arg1);
            return result;
        }
    }
    async adminLogin(arg0: string, arg1: string): Promise<AdminSession | null> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogin(arg0, arg1);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogin(arg0, arg1);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async adminLogout(arg0: AdminSessionToken): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminLogout(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminLogout(arg0);
            return result;
        }
    }
    async adminUnbanUser(arg0: AdminSessionToken, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminUnbanUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminUnbanUser(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n13(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async banUser(arg0: AdminSessionToken, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.banUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.banUser(arg0, arg1);
            return result;
        }
    }
    async cancelFriendRequest(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelFriendRequest(arg0);
            return result;
        }
    }
    async createPost(arg0: PostInput): Promise<PostView> {
        if (this.processError) {
            try {
                const result = await this.actor.createPost(await to_candid_PostInput_n15(this._uploadFile, this._downloadFile, arg0));
                return from_candid_PostView_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPost(await to_candid_PostInput_n15(this._uploadFile, this._downloadFile, arg0));
            return from_candid_PostView_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async createProduct(arg0: ProductInput): Promise<Product> {
        if (this.processError) {
            try {
                const result = await this.actor.createProduct(await to_candid_ProductInput_n20(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Product_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createProduct(await to_candid_ProductInput_n20(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Product_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async createReel(arg0: ReelInput): Promise<Reel> {
        if (this.processError) {
            try {
                const result = await this.actor.createReel(await to_candid_ReelInput_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Reel_n28(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReel(await to_candid_ReelInput_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Reel_n28(this._uploadFile, this._downloadFile, result);
        }
    }
    async createStory(arg0: StoryInput): Promise<Story> {
        if (this.processError) {
            try {
                const result = await this.actor.createStory(await to_candid_StoryInput_n32(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Story_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createStory(await to_candid_StoryInput_n32(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Story_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteComment(arg0: CommentId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteComment(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteComment(arg0);
            return result;
        }
    }
    async deleteFile(arg0: FileId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteFile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteFile(arg0);
            return result;
        }
    }
    async deletePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deletePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deletePost(arg0);
            return result;
        }
    }
    async deleteProduct(arg0: ProductId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteProduct(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteProduct(arg0);
            return result;
        }
    }
    async deleteReel(arg0: ReelId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReel(arg0);
            return result;
        }
    }
    async deleteStory(arg0: StoryId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteStory(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteStory(arg0);
            return result;
        }
    }
    async deleteUser(arg0: AdminSessionToken, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0, arg1);
            return result;
        }
    }
    async flagPost(arg0: PostId, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.flagPost(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.flagPost(arg0, arg1);
            return result;
        }
    }
    async getAdminStats(arg0: AdminSessionToken): Promise<AdminStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getAdminStats(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAdminStats(arg0);
            return result;
        }
    }
    async getAllUsers(arg0: AdminSessionToken, arg1: bigint, arg2: bigint): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers(arg0, arg1, arg2);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers(arg0, arg1, arg2);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAnalytics(arg0: AdminSessionToken): Promise<AnalyticsResult> {
        if (this.processError) {
            try {
                const result = await this.actor.getAnalytics(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAnalytics(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFlaggedPosts(arg0: AdminSessionToken): Promise<Array<PostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFlaggedPosts(arg0);
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFlaggedPosts(arg0);
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriendRequests(): Promise<Array<FriendView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendRequests();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendRequests();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriendSuggestions(): Promise<Array<FriendView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriendSuggestions();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriendSuggestions();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getFriends(): Promise<Array<FriendView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getFriends();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getFriends();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNewsfeed(): Promise<Array<PostView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNewsfeed();
                return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNewsfeed();
            return from_candid_vec_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getNotifications(): Promise<Array<Notification>> {
        if (this.processError) {
            try {
                const result = await this.actor.getNotifications();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getNotifications();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPostComments(arg0: PostId): Promise<Array<CommentView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPostComments(arg0);
                return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPostComments(arg0);
            return from_candid_vec_n54(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReels(arg0: bigint, arg1: bigint): Promise<Array<Reel>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReels(arg0, arg1);
                return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReels(arg0, arg1);
            return from_candid_vec_n55(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSentRequests(): Promise<Array<FriendView>> {
        if (this.processError) {
            try {
                const result = await this.actor.getSentRequests();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSentRequests();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStories(): Promise<Array<StoryGroup>> {
        if (this.processError) {
            try {
                const result = await this.actor.getStories();
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStories();
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async grantVerifiedTick(arg0: AdminSessionToken, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.grantVerifiedTick(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.grantVerifiedTick(arg0, arg1);
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async likePost(arg0: PostId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likePost(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likePost(arg0);
            return result;
        }
    }
    async likeReel(arg0: ReelId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.likeReel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.likeReel(arg0);
            return result;
        }
    }
    async listAdmins(arg0: AdminSessionToken): Promise<Array<string>> {
        if (this.processError) {
            try {
                const result = await this.actor.listAdmins(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listAdmins(arg0);
            return result;
        }
    }
    async listFiles(): Promise<Array<FileRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.listFiles();
                return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listFiles();
            return from_candid_vec_n60(this._uploadFile, this._downloadFile, result);
        }
    }
    async listProducts(): Promise<Array<Product>> {
        if (this.processError) {
            try {
                const result = await this.actor.listProducts();
                return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listProducts();
            return from_candid_vec_n63(this._uploadFile, this._downloadFile, result);
        }
    }
    async markAllNotificationsRead(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markAllNotificationsRead();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markAllNotificationsRead();
            return result;
        }
    }
    async markNotificationRead(arg0: NotifId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markNotificationRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markNotificationRead(arg0);
            return result;
        }
    }
    async markStoryViewed(arg0: StoryId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markStoryViewed(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markStoryViewed(arg0);
            return result;
        }
    }
    async moderatePost(arg0: AdminSessionToken, arg1: PostId, arg2: ModerationAction): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.moderatePost(arg0, arg1, to_candid_ModerationAction_n64(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.moderatePost(arg0, arg1, to_candid_ModerationAction_n64(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async rejectFriendRequest(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.rejectFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.rejectFriendRequest(arg0);
            return result;
        }
    }
    async removeAdmin(arg0: AdminSessionToken, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeAdmin(arg0, arg1);
            return result;
        }
    }
    async revokeVerifiedTick(arg0: AdminSessionToken, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.revokeVerifiedTick(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.revokeVerifiedTick(arg0, arg1);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: string, arg1: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0, await to_candid_opt_n66(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0, await to_candid_opt_n66(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async saveReel(arg0: ReelId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.saveReel(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveReel(arg0);
            return result;
        }
    }
    async sendFriendRequest(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.sendFriendRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendFriendRequest(arg0);
            return result;
        }
    }
    async unbanUser(arg0: AdminSessionToken, arg1: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unbanUser(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unbanUser(arg0, arg1);
            return result;
        }
    }
    async unfriend(arg0: UserId): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.unfriend(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unfriend(arg0);
            return result;
        }
    }
    async updateProfileAvatar(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfileAvatar(await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfileAvatar(await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProfileBio(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfileBio(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfileBio(arg0);
            return result;
        }
    }
    async updateProfileCoverPhoto(arg0: ExternalBlob): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfileCoverPhoto(await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfileCoverPhoto(await to_candid_ExternalBlob_n17(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateProfileUsername(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProfileUsername(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProfileUsername(arg0);
            return result;
        }
    }
    async uploadFile(arg0: FileInput): Promise<FileRecord> {
        if (this.processError) {
            try {
                const result = await this.actor.uploadFile(await to_candid_FileInput_n67(this._uploadFile, this._downloadFile, arg0));
                return from_candid_FileRecord_n61(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.uploadFile(await to_candid_FileInput_n67(this._uploadFile, this._downloadFile, arg0));
            return from_candid_FileRecord_n61(this._uploadFile, this._downloadFile, result);
        }
    }
    async validateAdminSession(arg0: AdminSessionToken): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.validateAdminSession(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateAdminSession(arg0);
            return result;
        }
    }
}
async function from_candid_CommentView_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CommentView): Promise<CommentView> {
    return await from_candid_record_n9(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_FileRecord_n61(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FileRecord): Promise<FileRecord> {
    return await from_candid_record_n62(_uploadFile, _downloadFile, value);
}
function from_candid_FriendStatus_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendStatus): FriendStatus {
    return from_candid_variant_n48(_uploadFile, _downloadFile, value);
}
async function from_candid_FriendView_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FriendView): Promise<FriendView> {
    return await from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function from_candid_NotifType_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _NotifType): NotifType {
    return from_candid_variant_n53(_uploadFile, _downloadFile, value);
}
function from_candid_Notification_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Notification): Notification {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
async function from_candid_PostView_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PostView): Promise<PostView> {
    return await from_candid_record_n19(_uploadFile, _downloadFile, value);
}
async function from_candid_Product_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Product): Promise<Product> {
    return await from_candid_record_n23(_uploadFile, _downloadFile, value);
}
async function from_candid_Reel_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Reel): Promise<Reel> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
async function from_candid_StoryGroup_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _StoryGroup): Promise<StoryGroup> {
    return await from_candid_record_n58(_uploadFile, _downloadFile, value);
}
async function from_candid_Story_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Story): Promise<Story> {
    return await from_candid_record_n35(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function from_candid__ImmutableObjectStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __ImmutableObjectStorageRefillResult): _ImmutableObjectStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_AdminSession]): AdminSession | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_opt_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n37(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PostId;
    likeCount: bigint;
    authorAvatar: [] | [_ExternalBlob];
    createdAt: _Timestamp;
    text: string;
    authorName: string;
    author: _UserId;
    authorIsVerified: boolean;
    commentCount: bigint;
    image: [] | [_ExternalBlob];
    likedByMe: boolean;
    flagCount: bigint;
}): Promise<{
    id: PostId;
    likeCount: bigint;
    authorAvatar?: ExternalBlob;
    createdAt: Timestamp;
    text: string;
    authorName: string;
    author: UserId;
    authorIsVerified: boolean;
    commentCount: bigint;
    image?: ExternalBlob;
    likedByMe: boolean;
    flagCount: bigint;
}> {
    return {
        id: value.id,
        likeCount: value.likeCount,
        authorAvatar: record_opt_to_undefined(await from_candid_opt_n10(_uploadFile, _downloadFile, value.authorAvatar)),
        createdAt: value.createdAt,
        text: value.text,
        authorName: value.authorName,
        author: value.author,
        authorIsVerified: value.authorIsVerified,
        commentCount: value.commentCount,
        image: record_opt_to_undefined(await from_candid_opt_n10(_uploadFile, _downloadFile, value.image)),
        likedByMe: value.likedByMe,
        flagCount: value.flagCount
    };
}
async function from_candid_record_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProductId;
    title: string;
    createdAt: _Timestamp;
    createdBy: _UserId;
    description: string;
    image: [] | [_ExternalBlob];
    price: number;
}): Promise<{
    id: ProductId;
    title: string;
    createdAt: Timestamp;
    createdBy: UserId;
    description: string;
    image?: ExternalBlob;
    price: number;
}> {
    return {
        id: value.id,
        title: value.title,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        description: value.description,
        image: record_opt_to_undefined(await from_candid_opt_n10(_uploadFile, _downloadFile, value.image)),
        price: value.price
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ReelId;
    title: string;
    authorId: _UserId;
    createdAt: _Timestamp;
    authorName: string;
    description: string;
    likedBy: Array<_UserId>;
    mediaUrl: _ExternalBlob;
    authorIsVerified: boolean;
    savedBy: Array<_UserId>;
    mediaType: _MediaType;
}): Promise<{
    id: ReelId;
    title: string;
    authorId: UserId;
    createdAt: Timestamp;
    authorName: string;
    description: string;
    likedBy: Array<UserId>;
    mediaUrl: ExternalBlob;
    authorIsVerified: boolean;
    savedBy: Array<UserId>;
    mediaType: MediaType;
}> {
    return {
        id: value.id,
        title: value.title,
        authorId: value.authorId,
        createdAt: value.createdAt,
        authorName: value.authorName,
        description: value.description,
        likedBy: value.likedBy,
        mediaUrl: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.mediaUrl),
        authorIsVerified: value.authorIsVerified,
        savedBy: value.savedBy,
        mediaType: from_candid_MediaType_n30(_uploadFile, _downloadFile, value.mediaType)
    };
}
async function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _StoryId;
    expiresAt: _Timestamp;
    authorId: _UserId;
    createdAt: _Timestamp;
    authorName: string;
    viewedBy: Array<_UserId>;
    image: _ExternalBlob;
}): Promise<{
    id: StoryId;
    expiresAt: Timestamp;
    authorId: UserId;
    createdAt: Timestamp;
    authorName: string;
    viewedBy: Array<UserId>;
    image: ExternalBlob;
}> {
    return {
        id: value.id,
        expiresAt: value.expiresAt,
        authorId: value.authorId,
        createdAt: value.createdAt,
        authorName: value.authorName,
        viewedBy: value.viewedBy,
        image: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.image)
    };
}
async function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _UserId;
    bio: [] | [string];
    username: string;
    createdAt: _Timestamp;
    coverPhoto: [] | [_ExternalBlob];
    isVerified: boolean;
    isBanned: boolean;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    id: UserId;
    bio?: string;
    username: string;
    createdAt: Timestamp;
    coverPhoto?: ExternalBlob;
    isVerified: boolean;
    isBanned: boolean;
    avatar?: ExternalBlob;
}> {
    return {
        id: value.id,
        bio: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.bio)),
        username: value.username,
        createdAt: value.createdAt,
        coverPhoto: record_opt_to_undefined(await from_candid_opt_n10(_uploadFile, _downloadFile, value.coverPhoto)),
        isVerified: value.isVerified,
        isBanned: value.isBanned,
        avatar: record_opt_to_undefined(await from_candid_opt_n10(_uploadFile, _downloadFile, value.avatar))
    };
}
async function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _FriendStatus;
    mutualFriendCount: bigint;
    username: string;
    userId: _UserId;
    avatar: [] | [_ExternalBlob];
}): Promise<{
    status: FriendStatus;
    mutualFriendCount: bigint;
    username: string;
    userId: UserId;
    avatar?: ExternalBlob;
}> {
    return {
        status: from_candid_FriendStatus_n47(_uploadFile, _downloadFile, value.status),
        mutualFriendCount: value.mutualFriendCount,
        username: value.username,
        userId: value.userId,
        avatar: record_opt_to_undefined(await from_candid_opt_n10(_uploadFile, _downloadFile, value.avatar))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _NotifId;
    actorName: string;
    notifType: _NotifType;
    userId: _UserId;
    createdAt: _Timestamp;
    isRead: boolean;
    actorId: _UserId;
    message: string;
    targetType: [] | [string];
    targetId: [] | [bigint];
}): {
    id: NotifId;
    actorName: string;
    notifType: NotifType;
    userId: UserId;
    createdAt: Timestamp;
    isRead: boolean;
    actorId: UserId;
    message: string;
    targetType?: string;
    targetId?: bigint;
} {
    return {
        id: value.id,
        actorName: value.actorName,
        notifType: from_candid_NotifType_n52(_uploadFile, _downloadFile, value.notifType),
        userId: value.userId,
        createdAt: value.createdAt,
        isRead: value.isRead,
        actorId: value.actorId,
        message: value.message,
        targetType: record_opt_to_undefined(from_candid_opt_n39(_uploadFile, _downloadFile, value.targetType)),
        targetId: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.targetId))
    };
}
async function from_candid_record_n58(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    authorId: _UserId;
    stories: Array<_Story>;
    authorName: string;
}): Promise<{
    authorId: UserId;
    stories: Array<Story>;
    authorName: string;
}> {
    return {
        authorId: value.authorId,
        stories: await from_candid_vec_n59(_uploadFile, _downloadFile, value.stories),
        authorName: value.authorName
    };
}
async function from_candid_record_n62(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FileId;
    title: string;
    uploaderName: string;
    blob: _ExternalBlob;
    description: string;
    uploadedAt: _Timestamp;
    uploadedBy: _UserId;
}): Promise<{
    id: FileId;
    title: string;
    uploaderName: string;
    blob: ExternalBlob;
    description: string;
    uploadedAt: Timestamp;
    uploadedBy: UserId;
}> {
    return {
        id: value.id,
        title: value.title,
        uploaderName: value.uploaderName,
        blob: await from_candid_ExternalBlob_n11(_uploadFile, _downloadFile, value.blob),
        description: value.description,
        uploadedAt: value.uploadedAt,
        uploadedBy: value.uploadedBy
    };
}
async function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _CommentId;
    authorAvatar: [] | [_ExternalBlob];
    createdAt: _Timestamp;
    text: string;
    authorName: string;
    author: _UserId;
    postId: _PostId;
}): Promise<{
    id: CommentId;
    authorAvatar?: ExternalBlob;
    createdAt: Timestamp;
    text: string;
    authorName: string;
    author: UserId;
    postId: PostId;
}> {
    return {
        id: value.id,
        authorAvatar: record_opt_to_undefined(await from_candid_opt_n10(_uploadFile, _downloadFile, value.authorAvatar)),
        createdAt: value.createdAt,
        text: value.text,
        authorName: value.authorName,
        author: value.author,
        postId: value.postId
    };
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    video: null;
} | {
    image: null;
}): MediaType {
    return "video" in value ? MediaType.video : "image" in value ? MediaType.image : value;
}
function from_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    none: null;
} | {
    sent: null;
} | {
    friends: null;
} | {
    received: null;
}): FriendStatus {
    return "none" in value ? FriendStatus.none : "sent" in value ? FriendStatus.sent : "friends" in value ? FriendStatus.friends : "received" in value ? FriendStatus.received : value;
}
function from_candid_variant_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    like_post: null;
} | {
    friend_accept: null;
} | {
    comment_post: null;
} | {
    verified_granted: null;
} | {
    friend_request: null;
}): NotifType {
    return "like_post" in value ? NotifType.like_post : "friend_accept" in value ? NotifType.friend_accept : "comment_post" in value ? NotifType.comment_post : "verified_granted" in value ? NotifType.verified_granted : "friend_request" in value ? NotifType.friend_request : value;
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n37(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PostView>): Promise<Array<PostView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_PostView_n18(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FriendView>): Promise<Array<FriendView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FriendView_n45(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Notification>): Array<Notification> {
    return value.map((x)=>from_candid_Notification_n50(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_CommentView>): Promise<Array<CommentView>> {
    return await Promise.all(value.map(async (x)=>await from_candid_CommentView_n8(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Reel>): Promise<Array<Reel>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Reel_n28(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_StoryGroup>): Promise<Array<StoryGroup>> {
    return await Promise.all(value.map(async (x)=>await from_candid_StoryGroup_n57(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n59(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Story>): Promise<Array<Story>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Story_n34(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n60(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FileRecord>): Promise<Array<FileRecord>> {
    return await Promise.all(value.map(async (x)=>await from_candid_FileRecord_n61(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n63(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Product>): Promise<Array<Product>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Product_n22(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_FileInput_n67(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FileInput): Promise<_FileInput> {
    return await to_candid_record_n68(_uploadFile, _downloadFile, value);
}
function to_candid_MediaType_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_ModerationAction_n64(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModerationAction): _ModerationAction {
    return to_candid_variant_n65(_uploadFile, _downloadFile, value);
}
async function to_candid_PostInput_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PostInput): Promise<_PostInput> {
    return await to_candid_record_n16(_uploadFile, _downloadFile, value);
}
async function to_candid_ProductInput_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProductInput): Promise<_ProductInput> {
    return await to_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function to_candid_ReelInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReelInput): Promise<_ReelInput> {
    return await to_candid_record_n25(_uploadFile, _downloadFile, value);
}
async function to_candid_StoryInput_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: StoryInput): Promise<_StoryInput> {
    return await to_candid_record_n33(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation): __ImmutableObjectStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ImmutableObjectStorageRefillInformation | null): [] | [__ImmutableObjectStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__ImmutableObjectStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n66(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value));
}
async function to_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: string;
    image?: ExternalBlob;
}): Promise<{
    text: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        text: value.text,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
async function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    image?: ExternalBlob;
    price: number;
}): Promise<{
    title: string;
    description: string;
    image: [] | [_ExternalBlob];
    price: number;
}> {
    return {
        title: value.title,
        description: value.description,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.image)) : candid_none(),
        price: value.price
    };
}
async function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    mediaUrl: ExternalBlob;
    mediaType: MediaType;
}): Promise<{
    title: string;
    description: string;
    mediaUrl: _ExternalBlob;
    mediaType: _MediaType;
}> {
    return {
        title: value.title,
        description: value.description,
        mediaUrl: await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.mediaUrl),
        mediaType: to_candid_MediaType_n26(_uploadFile, _downloadFile, value.mediaType)
    };
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    image: ExternalBlob;
}): Promise<{
    image: _ExternalBlob;
}> {
    return {
        image: await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.image)
    };
}
async function to_candid_record_n68(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    blob: ExternalBlob;
    description: string;
}): Promise<{
    title: string;
    blob: _ExternalBlob;
    description: string;
}> {
    return {
        title: value.title,
        blob: await to_candid_ExternalBlob_n17(_uploadFile, _downloadFile, value.blob),
        description: value.description
    };
}
function to_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    video: null;
} | {
    image: null;
} {
    return value == MediaType.video ? {
        video: null
    } : value == MediaType.image ? {
        image: null
    } : value;
}
function to_candid_variant_n65(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ModerationAction): {
    approve: null;
} | {
    delete: null;
} {
    return value == ModerationAction.approve ? {
        approve: null
    } : value == ModerationAction.delete ? {
        delete_: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
